
services:
  order-service:
    build:
      context: ./src
      dockerfile: order_service/Dockerfile
    container_name: order-service
    environment:
      - FLASK_APP=order_service.wsgi:app
      - FLASK_ENV=${FLASK_ENV}
      - MONGO_URI=${MONGO_URI}
      - DATABASE_NAME=${DATABASE_NAME}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_ORDER_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_ORDER_PASSWORD}
      - RABBITMQ_QUEUE_NAME=${RABBITMQ_QUEUE_NAME}
    ports:
      - "5001:5000"


  user-service-v1:
    build:
      context: ./src
      dockerfile: user_service_v1/Dockerfile
    container_name: user-service-v1
    environment:
      - FLASK_APP=user_service_v1.wsgi:app
      - FLASK_ENV=${FLASK_ENV}
      - MONGO_URI=${MONGO_URI}
      - DATABASE_NAME=${DATABASE_NAME}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_USER_PASSWORD}
      - RABBITMQ_QUEUE_NAME=${RABBITMQ_QUEUE_NAME}
    ports:
      - "5002:5000"

  
  user-service-v2:
    build:
      context: ./src
      dockerfile: user_service_v2/Dockerfile
    container_name: user-service-v2
    environment:
      - FLASK_APP=user_service_v2.wsgi:app
      - FLASK_ENV=${FLASK_ENV}
      - MONGO_URI=${MONGO_URI}
      - DATABASE_NAME=${DATABASE_NAME}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_USER_PASSWORD}
      - RABBITMQ_QUEUE_NAME=${RABBITMQ_QUEUE_NAME}
    ports:
      - "5003:5000"

  
  kong:
    image: kong:latest
    container_name: api-gateway
    build:
      context: ./src/api_gateway
      dockerfile: Dockerfile
      args: 
        - P_VALUE=${P_VALUE}
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - P_VALUE=${P_VALUE}
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    depends_on:
      - order-service
      - user-service-v1

  konga: 
    container_name: api-gateway-ui
    image: pantsel/konga:latest
    environment:
      - NODE_ENV=production
    ports:
      - "1337:1337"
